### PR TITLE
Improve safety doc-string for `Dependencies` trait

### PR DESCRIPTION
**Pull request by vccggorski**
Overlooked in #18.

### CODE REVIEW

**Review by vccnfitingh — APPROVED** [review]
ok

**Review by vccnfitingh — CHANGES_REQUESTED** [review]
While we are at it, I noticed that the docs for `eligible_message_ram_start` still assumes 32-bit addresses in

> Only 2 most significant bytes are relevant.

A TODO comment in #20 references some safety guarantee about the contents of the 2 least significant bytes of the address, but I don't see it here. I think we should change the part about the relevant bits to

> The two least significant bytes must be zero, or in other words, the address must be aligned to `u16::MAX + 1`.

**Comment by vccggorski** [comment]
Fixed

**Review by vccnfitingh — APPROVED** [review]
Looks fixed to me

**Pull request merged**
